apiVersion: v2
name: go-ratelimit
description: A Ratelimit Service Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.4.0
dependencies:
  - name: redis
    version: 6.4.2
    repository: https://kubernetes-charts.storage.googleapis.com
