{{- range .Values.virtualHosts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "go-ratelimit.labels" . | nindent 4 }}
data:
  config-{{ .name }}.yaml: |
{{ toYaml .config | indent 2 }}
{{- end }}
