apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-ratelimit.fullname" . }}
  labels:
    {{- include "go-ratelimit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-ratelimit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-ratelimit.selectorLabels" . | nindent 8 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "go-ratelimit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
          - name: LOG_LEVEL
            value: debug
{{- if .Values.redish.enabled }}
          - name: REDIS_SOCKET_TYPE
            value: {{ .Values.redisSocketType }}
          - name: REDIS_URL
            value: {{ .Values.redisUrl }}:{{ .Values.redisPort }}
{{- end }}
          - name: RUNTIME_ROOT
            value: /data
          - name: RUNTIME_SUBDIRECTORY
            value: ratelimit
          - name: USE_STATSD
            value: "false"
          name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: http-debug 
              containerPort: {{ .Values.debugPort }}
            - name: grpc-server
              containerPort: {{ .Values.grpcPort }}
            - name: http-server
              containerPort: {{ .Values.httpPort }}
{{- range .Values.virtualHosts }}
          volumeMounts:
          - mountPath: /data/ratelimit/config/config-{{ .name }}.yaml
            name: config-{{ .name }}.yaml
            subPath: config-{{ .name }}.yaml
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- range .Values.virtualHosts }}
      volumes:
      - configMap:
          defaultMode: 420
          name: config-{{ .name }}.yaml
        name: config-{{ .name }}.yaml
{{- end }}
